### ISSUE TITLE
Layout tile group - allow groups without "label"

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/wag#875]
Such a group should be separated from the previous one (i.e. not applicable in case it is the first group) using a horizontal separator (style will be discussed).

**Comment by tomachalek** [comment]
Additional notes:

1.The decision on whether to show/hide label elements should be driven solely by `groupLabel`. 
2. `groupDescURL` should become optional

**Comment by mzimandl** [comment]
ad 2. - already done
