### ISSUE TITLE
What API are you using?

### ISSUE THREAD

**Issue by MaTY-MT** [czcorpus/wag#917]
Hi,
I don't really want to dig into your code, can you please tell me what API are you using? And is that API public, so I can use it for my project?

Thanks.

**Comment by tomachalek** [comment]
Hello @MaTY-MT ,

a list of currently supported APIs is at the homepage: https://github.com/czcorpus/wag#currently-supported-resources. In general, supported API depends on type of a tile. In case you would like to see some other API supported by WaG, please let us know. We cannot guarantee that all requests will be accepted but we are definitely willing to think about suggestions. As a simple rule-of-thumb - the more widely known the API is, the higher chance is that it will be included.

**Comment by MaTY-MT** [comment]
Oh, thanks. I needed the API for recognising the part of speech.
